image: pnxs/dots_devenv:20.04.1

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build_ubuntu:
    stage: build
    before_script:
        - python3 -m pip install dots-code-generator 
    script:
        - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_VERSION_PATCH=${CI_PIPELINE_ID}
        - make -Cbuild -j4
        - cd build && cpack && cd -
        - cp build/dots-cpp-dev_*.deb build/dots-cpp-dev_amd64.deb
    artifacts:
        paths:
            - ./build/lib/libdots.a
            - ./build/bin/dotsd/dotsd
            - ./build/bin/examples/testClient/testClient
            - ./build/tests/dots-unittests
            - ./build/dots-cpp_*.deb
            - ./build/dots-cpp-dev_*.deb
            - ./build/dots-cpp-testclient_*.deb

run_unittests:
    stage: test
    dependencies:
        - build_ubuntu
    script:
        - ./build/tests/dots-unittests --gtest_output="xml:report.xml"
    artifacts:
        reports:
            junit:
                - report.xml

deploy:
    stage: deploy
    script:
        - "curl -X POST -F token=${TRIGGER_TOKEN_DOTS_LEGACY} -F ref=${CI_COMMIT_BRANCH} -F \"variables[DOTS_LIB_NAME]=build/dots-cpp-dev_1.1.${CI_PIPELINE_ID}_amd64.deb?job=build_ubuntu\" -F \"variables[TRIGGER_BRANCH]=${CI_COMMIT_BRANCH}\" -F \"variables[TRIGGER_JOB_ID]=${CI_JOB_ID}\" https://git2.pnxs.de/api/v4/projects/34/trigger/pipeline"
