
image: pnxs/dots_devenv:2

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build_ubuntu:
    stage: build
    script:
        - pwd
        - cmake -Bbuild -H.
        - make -Cbuild -j4
    artifacts:
        paths:
            - ./build/dots-cpp/lib/libdots.a
            - ./build/dots-cpp/bin/dotsd/dotsd
            - ./build/dots-cpp/bin/examples/testClient/testClient
            - ./build/dots-cpp/tests/dots-unittests
            - ./build/dots-cpp-legacy/lib/dots_legacy/libdots_legacy.a
            - ./build/dots-cpp-legacy/bin/dotsctl/dots
            - ./build/dots-cpp-legacy/bin/dots-persistd/dots-persistd
            - ./build/dots-cpp-legacy/bin/dots-web-connector/dots-web-connector
            - ./build/dots-cpp-legacy/lib/dots_legacy/tests/dots_legacy-unittests

run_unittests:
    stage: test
    dependencies:
        - build_ubuntu
    script:
        - pwd
        - find
        - ./build/dots-cpp/tests/dots-unittests --gtest_output="xml:report.xml"
        - ./build/dots-cpp-legacy/lib/dots_legacy/tests/dots_legacy-unittests --gtest_output="xml:report_legacy.xml"
    artifacts:
        reports:
            junit:
                - report.xml
                - report_legacy.xml