
image: pnxs/dots_devenv:18.10

variables:
    GIT_SUBMODULE_STRATEGY: recursive

ubuntu:
    stage: build
    script:
        - cmake -Bbuild -H. -DBUILD_XDOTS=OFF
        - make -Cbuild -j4

run_unittests:
    stage: test
    script:
        - ./build/bin/dotsd/tests/dotsd-unittests
        - ./build/lib/dots/tests/dots-unittests

